# Generated by Django 5.1.1 on 2024-11-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
