# Generated by Django 5.1.1 on 2024-11-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reputation',
        ),
    ]
