# Generated by Django 5.1.1 on 2024-11-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_profile_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='stock_restante',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
