# Generated by Django 5.1.1 on 2024-11-11 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_detallecompra_stock_restante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecompra',
            name='stock_restante',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
