# Generated by Django 5.1.1 on 2024-11-12 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_detallecompra_stock_restante_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='stock_restante',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.producto'),
        ),
    ]
