# Generated by Django 5.1.1 on 2024-11-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_calificacionproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('preparacion', 'En Preparación'), ('camino', 'En Camino'), ('entregado', 'Entregado')], default='pendiente', max_length=15)),
                ('pagado', models.BooleanField(default=False)),
            ],
        ),
    ]
