# Generated by Django 5.1.1 on 2024-11-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pagado', 'Pagado'), ('preparacion', 'En Preparación'), ('camino', 'En Camino'), ('entregado', 'Entregado')], default='pagado', max_length=15),
        ),
    ]
